### ISSUE TITLE
too many open files 버그 

### ISSUE THREAD

**Issue by kybin** [studio2l/roi#432]
```
2020/01/11 11:56:38 http: Accept error: accept tcp 167.179.80.33:443: accept4: too many open files; retrying in 1s
goroutine 26453 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010990, 0xc000059f67, 0xc000125e00)
	/usr/local/go/src/net/http/h2_bundle.go:5706 +0x16b
panic(0x917f20, 0xc000314dc0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
main.parseTemplate()
	/root/src/github.com/studio2l/roi/cmd/roi/template.go:31 +0x4f1
main.executeTemplate(0xa81400, 0xc000010990, 0x9c0bb1, 0xa, 0x0, 0x0, 0x0, 0x8)
	/root/src/github.com/studio2l/roi/cmd/roi/template.go:20 +0xe4
main.loginHandler(0xa81400, 0xc000010990, 0xc0001a0c00, 0xc0000109e8, 0x9bc9f6, 0x6)
	/root/src/github.com/studio2l/roi/cmd/roi/user_handler.go:39 +0x84
main.handle.func1(0xa81400, 0xc000010990, 0xc0001a0c00)
	/root/src/github.com/studio2l/roi/cmd/roi/handler.go:44 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc000193d00, 0xa81400, 0xc000010990, 0xc0001a0c00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001a8c40, 0xa81400, 0xc000010990, 0xc0001a0c00)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0001b0000, 0xa81400, 0xc000010990, 0xc0001a0c00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0xa82900, 0xc000455b90, 0xc0000eb880, 0xc0001b0000, 0xa81400, 0xc000010990, 0xc0001a0c00)
	/usr/local/go/src/net/http/server.go:3366 +0x8d
net/http.(*http2serverConn).runHandler(0xc000125e00, 0xc000010990, 0xc0001a0c00, 0xc00035a400)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5447 +0x4eb
```

**Comment by kybin** [comment]
db 연결을 잘 닫아주고 난 후에 사라진 것 같다.
